apiVersion: apps/v1
kind: Deployment
metadata:
  name: soniya-todo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soniya-todo-frontend
  template:
    metadata:
      labels:
        app: soniya-todo-frontend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "soniya-todo-frontend"
        dapr.io/app-port: "3000"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: soniya-todo-frontend
        image: soniya-todo-frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: soniya-todo-frontend
spec:
  selector:
    app: soniya-todo-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
